In [3]:
import pandas as pd
import tensorflow as tf
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn import neighbors
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.cluster import KMeans
from sklearn.naive_bayes import GaussianNB
from sklearn import model_selection
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import BaggingClassifier
from keras.models import Sequential
from keras.layers import Dense
from tensorflow.keras import models, layers
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
#from pyDeepInsight import ImageTransformer, LogScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from keras.callbacks import EarlyStopping
from matplotlib import pyplot as plt
import seaborn as sns

In [5]:
df = pd.read_csv(r'C:\Users\anive\Documents\GitHub\Traffic-classification-and-mitigation-of-DDoS-Attack-in-SDN-\sdn_traffic_dataset.csv')
df.shape

(104345, 23)

In [6]:
df.size

2399935

In [7]:
df.sample(10)

,dt,switch,src,dst,pktcount,bytecount,dur,dur_nsec,tot_dur,flows,...,pktrate,Pairflow,Protocol,port_no,tx_bytes,rx_bytes,tx_kbps,rx_kbps,tot_kbps,label
2086,12205,2,10.0.0.4,10.0.0.8,134997,143906802,310,738000000,3.110000e+11,2,...,294,0,UDP,1,4428,125155754,0,3841.0,3841.0,1
74987,41163,6,10.0.0.11,10.0.0.3,94683,104548982,213,339000000,2.130000e+11,7,...,444,1,TCP,1,4532669,106370140,168,4045.0,4213.0,0
72198,7747,8,10.0.0.3,10.0.0.16,23714,1375412,94,731000000,9.473100e+10,5,...,298,1,TCP,1,8908,1312,0,0.0,0.0,0
17613,11575,5,10.0.0.20,10.0.0.8,125347,130611574,400,810000000,4.010000e+11,2,...,311,0,UDP,3,143928701,3917,0,0.0,0.0,1
56369,33183,2,10.0.0.2,10.0.0.5,7,686,8,283000000,8.283000e+09,9,...,0,1,ICMP,2,135465626,1942,0,0.0,0.0,0
45827,31903,1,10.0.0.1,10.0.0.15,113818,6601444,417,869000000,4.180000e+11,5,...,252,1,TCP,1,463192367,33327906,426,229.0,655.0,0
52539,28338,4,10.0.0.7,10.0.0.1,131703,135626894,1551,403000000,1.550000e+12,13,...,0,1,ICMP,1,542500307,540830578,4,4.0,8.0,1
89180,25200,4,10.0.0.10,10.0.0.5,139,13622,143,74000000,1.430000e+11,7,...,0,1,ICMP,1,5646,1472,0,0.0,0.0,0
27710,3399,4,10.0.0.3,10.0.0.5,61270,63843340,196,838000000,1.970000e+11,3,...,306,0,UDP,1,4652,207933506,0,2553.0,2553.0,1
157,11425,1,10.0.0.2,10.0.0.8,90333,96294978,200,744000000,2.010000e+11,3,...,451,0,UDP,1,3879,48410560,0,3838.0,3838.0,0

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 104345 entries, 0 to 104344
Data columns (total 23 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   dt           104345 non-null  int64
 1   switch       104345 non-null  int64
 2   src          104345 non-null  object
 3   dst          104345 non-null  object
 4   pktcount     104345 non-null  int64
 5   bytecount    104345 non-null  int64
 6   dur          104345 non-null  int64
 7   dur_nsec     104345 non-null  int64
 8   tot_dur      104345 non-null  float64
 9   flows        104345 non-null  int64
 10  packetins    104345 non-null  int64
 11  pktperflow   104345 non-null  int64
 12  byteperflow  104345 non-null  int64
 13  pktrate      104345 non-null  int64
 14  Pairflow     104345 non-null  int64
 15  Protocol     104345 non-null  object
 16  port_no      104345 non-null  int64
 17  tx_bytes     104345 non-null  int64
 18  rx_bytes     104345 non-null  int64
 19  tx_kbps      104345 non-null  int64
 20  rx_kbps      103839 non-null  float64
 21  tot_kbps     103839 non-null  float64
 22  label        104345 non-null  int64
dtypes: float64(3), int64(17), object(3)
memory usage: 18.3+ MB

In [10]:
df.isna().sum()

dt               0
switch           0
src              0
dst              0
pktcount         0
bytecount        0
dur              0
dur_nsec         0
tot_dur          0
flows            0
packetins        0
pktperflow       0
byteperflow      0
pktrate          0
Pairflow         0
Protocol         0
port_no          0
tx_bytes         0
rx_bytes         0
tx_kbps          0
rx_kbps        506
tot_kbps       506
label            0
dtype: int64

In [11]:
df.head()

,dt,switch,src,dst,pktcount,bytecount,dur,dur_nsec,tot_dur,flows,...,pktrate,Pairflow,Protocol,port_no,tx_bytes,rx_bytes,tx_kbps,rx_kbps,tot_kbps,label
0,11425,1,10.0.0.1,10.0.0.8,45304,48294064,100,716000000,1.010000e+11,3,...,451,0,UDP,3,143928631,3917,0,0.0,0.0,0
1,11605,1,10.0.0.1,10.0.0.8,126395,134737070,280,734000000,2.810000e+11,2,...,451,0,UDP,4,3842,3520,0,0.0,0.0,0
2,11425,1,10.0.0.2,10.0.0.8,90333,96294978,200,744000000,2.010000e+11,3,...,451,0,UDP,1,3795,1242,0,0.0,0.0,0
3,11425,1,10.0.0.2,10.0.0.8,90333,96294978,200,744000000,2.010000e+11,3,...,451,0,UDP,2,3688,1492,0,0.0,0.0,0
4,11425,1,10.0.0.2,10.0.0.8,90333,96294978,200,744000000,2.010000e+11,3,...,451,0,UDP,3,3413,3665,0,0.0,0.0,0

In [12]:
df.drop(['dt', 'switch', 'src', 'dst'],axis=1,inplace=True)
df.head()

,pktcount,bytecount,dur,dur_nsec,tot_dur,flows,packetins,pktperflow,byteperflow,pktrate,Pairflow,Protocol,port_no,tx_bytes,rx_bytes,tx_kbps,rx_kbps,tot_kbps,label
0,45304,48294064,100,716000000,1.010000e+11,3,1943,13535,14428310,451,0,UDP,3,143928631,3917,0,0.0,0.0,0
1,126395,134737070,280,734000000,2.810000e+11,2,1943,13531,14424046,451,0,UDP,4,3842,3520,0,0.0,0.0,0
2,90333,96294978,200,744000000,2.010000e+11,3,1943,13534,14427244,451,0,UDP,1,3795,1242,0,0.0,0.0,0
3,90333,96294978,200,744000000,2.010000e+11,3,1943,13534,14427244,451,0,UDP,2,3688,1492,0,0.0,0.0,0
4,90333,96294978,200,744000000,2.010000e+11,3,1943,13534,14427244,451,0,UDP,3,3413,3665,0,0.0,0.0,0

In [13]:
df.shape

(104345, 19)

In [15]:
df.Protocol.unique()

array(['UDP', 'TCP', 'ICMP'], dtype=object)

In [16]:
df.label.unique()

array([0, 1], dtype=int64)